language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.7-dev"
install:
  - pip install flake8 codecov tox-travis
before_script:
  - flake8 --exclude=test_* setup.py
  - flake8 --exclude=test_* tfeco/
script: tox
after_success:
  - codecov
