language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
matrix:
  allow_failures:
  - python: 3.7-dev
install:
- pip install flake8 codecov tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: drewsonne
  password: $PYPI_PASSWORD
  on:
    tags: true
